"""auto update

Revision ID: 48957c546d21
Revises: 78d841672338
Create Date: 2026-03-16 12:04:16.340213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48957c546d21'
down_revision: Union[str, Sequence[str], None] = '78d841672338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_progress', sa.Column('login_streak', sa.Integer(), nullable=True))
    op.add_column('player_progress', sa.Column('last_login_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_progress', 'last_login_date')
    op.drop_column('player_progress', 'login_streak')
    # ### end Alembic commands ###