"""auto update

Revision ID: f7ccb346a580
Revises: 
Create Date: 2026-03-16 00:25:40.319278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ccb346a580'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('total_won', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('prestige_level', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_entries_id'), 'leaderboard_entries', ['id'], unique=False)
    op.create_table('player_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('total_drops', sa.Integer(), nullable=True),
    sa.Column('total_won', sa.Float(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('biggest_win', sa.Float(), nullable=True),
    sa.Column('tap_count', sa.Integer(), nullable=True),
    sa.Column('combo_count', sa.Integer(), nullable=True),
    sa.Column('max_combo', sa.Integer(), nullable=True),
    sa.Column('consecutive_losses', sa.Integer(), nullable=True),
    sa.Column('prestige_level', sa.Integer(), nullable=True),
    sa.Column('selected_skin', sa.String(), nullable=True),
    sa.Column('selected_theme', sa.String(), nullable=True),
    sa.Column('owned_skins', sa.String(), nullable=True),
    sa.Column('owned_themes', sa.String(), nullable=True),
    sa.Column('active_boosters', sa.String(), nullable=True),
    sa.Column('shop_purchases', sa.Integer(), nullable=True),
    sa.Column('achievements', sa.String(), nullable=True),
    sa.Column('daily_challenges', sa.String(), nullable=True),
    sa.Column('weekly_challenges', sa.String(), nullable=True),
    sa.Column('last_daily_bonus', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_hourly_bonus', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_wheel_spin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_progress_id'), 'player_progress', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_player_progress_id'), table_name='player_progress')
    op.drop_table('player_progress')
    op.drop_index(op.f('ix_leaderboard_entries_id'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    # ### end Alembic commands ###